### ISSUE TITLE
img ma'noga emas bo'lsa psevda elementlar bilan joylagan ma'qulmikan

### ISSUE THREAD

**Issue by Shukurjonov** [rustami-dastan/scoot#4]
![image](https://user-images.githubusercontent.com/79937058/117444157-82b4d400-af52-11eb-9076-3a5f84951f8f.png)
Bu yerda rasm sarlavhani izohlab ketyapti faqat menimcha, before, after bilan joylagan ma'qul

**Comment by rustamidastan** [comment]
issue is fixed
